{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-stack.fullname" . }}-backend
  labels:
    {{- include "app-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      {{- include "app-stack.backendSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app-stack.backendSelectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: backend
          image: {{ .Values.global.imageRegistry }}{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            {{- toYaml .Values.backend.env | nindent 12 }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
